name: CI test

on: 
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  ci: 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: setup node 
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Configure AWS Credentials for NPM tokens
        uses: mapbox/configure-aws-credentials-internal@v3
        with:
          target-account-id: '234858372212'
      - name: Retrieve and Configure NPM Token
        uses: mapbox/setup-npm-token@v1.1
      - run: npm ci

      - name: lint
        run: npm run lint

      - name: test
        run: npm run test   